version: '3.4'

services:
  html:
    build:
      context: .
      dockerfile: Dockerfile.asciidoctor
    volumes:
      - ./:/workdir
    command: asciidoctor -n ap-dmp.adoc

  pdf:
    build:
      context: .
      dockerfile: Dockerfile.asciidoctor
    volumes:
      - ./:/workdir
    command: asciidoctor-pdf -a pdf-themesdir=./ -a pdf-theme=ap -n ap-dmp.adoc
